### ISSUE TITLE
Upgrade cson dependencies

### ISSUE THREAD

**Issue by ehmicky** [stevelacy/gulp-cson#1]
The current cson dependency version depends on coffee-script 1.8.0. This version of coffee-script does not run on Node 0.12 as it uses the `vm` module which had API changes. coffee-script 1.9.0 fixed this, which cson ^2.0.0 uses.
So unless cson dependency is updated to ^2.0.0, gulp-cson currently breaks on Node 0.12.

**Comment by stephenlacy** [comment]
Fixed and published to `gulp-cson@0.2.0`
