### ISSUE TITLE
gulp-cson breaks on parse error

### ISSUE THREAD

**Issue by bigmomma** [stevelacy/gulp-cson#2]
you used a undefined variable 'err' in index.coffee on line 11.

It should read:
    return cb json if json instanceof Error
instead of:
    return cb err if json instanceof Error

**Comment by floscher** [comment]
<del>That doesn't seem to resolve the issue. The gulp-task would then finish normally without generating the destination files and dependent tasks would not be executed.</del>

**Comment by bigmomma** [comment]
umm the issue was that it crashed if there was an error parsing .cson files, complaining that 'err' was undefined. I didn't really look beyond that issue.
But, by a quick look at the map-stream documentation, it seems to me that calling the callback with the error object should emit an error event on the stream. Which seems to be the expected behaviour..? or not?

**Comment by stephenlacy** [comment]
As @floscher said it would just continue with null as the err var was null.

I Fixed the returned error and added a test for it in `0.2.1`

**Comment by bigmomma** [comment]
@stevelacy, thx for the fix.
I don't quite understand how the change you applied is any different from what I suggested. Could you please explain?

**Comment by floscher** [comment]
Thank you @stevelacy!

@bigmomma I was wrong. The line I tested was

``` cson
return cb if json instanceof Error
```

instead of

``` cson
return cb json if json instanceof Error
```

I should read more carefully next time.

**Comment by floscher** [comment]
Would it easily be possible to output the name of the file in which the parsing error occured?

When processing multiple cson-files, it would be helpful to know which one is flawed.

Currently the output on error shows only the line number in standard input, e.g.:

```
        throw err
              ^
Error: [stdin]:29:3: error: unmatched ]
  ]
  ^
```
